### PR TITLE
fix security issues / vulnerabilities reported by npm audit

### PR DESCRIPTION
**Pull request by bluet**
I've got a lot of security warning emails from projects using harp.

Summary:
1. Fix security warning by updating html-minifier.
2. `npm run test` passed.

### CODE REVIEW

**Comment by bluet** [comment]
@sintaxi @jorgepedret please kindly review, and if it's ok, expecting to have it published as new version on npmjs, and have `harp` and `terraform` to use the new version as dependency to solve security issue. Thanks!

**Comment by sintaxi** [comment]
Thanks for your work!

**Comment by bluet** [comment]
@sintaxi Thanks for your quick response!
Will you publish new version to npmjs and update the dependency tree in terraform and harp any time soon? :-)

**Comment by sintaxi** [comment]
@kennethormandy hey, any chance you can grant me publishing rights to npm for this repo?

**Comment by bluet** [comment]
@kennethormandy people are crying, expecting a new release on npmjs lol

**Pull request merged**
